# We use legacy Yarn v1.22.4 by default:
yarnPath: .yarn/releases/yarn-1.22.4.cjs

# Switch to this path if want to use Yarn v2.
# Please remember to run `yarn install` when switching
#  between versions because of differences in `yarn.lock` file.
# yarnPath: .yarn/releases/yarn-2.0.0-rc.36.cjs
