#!/bin/bash

set -e

# Run this using `yarn pack:zip` to get package name and version injected
zip $npm_package_name-$npm_package_version.zip -qr dist node_modules package.json \
  && echo "Succesfully packaged $npm_package_name-$npm_package_version.zip" || echo "Failure!"
