# .github/workflows/nodejs.yml
name: Node CI

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x] # Only run the 10.x build

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install, lint, build, and test
        run: |
          yarn
          yarn lint
          yarn build
          yarn test
      - name: yarn package
        run: yarn package
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: near-protocol-adapter-${{steps.package-version.outputs.current-version}}
          path: near-protocol-adapter-${{steps.package-version.outputs.current-version}}.zip
